### ISSUE TITLE
GitIgnore Dosyası

### ISSUE THREAD

**Issue by emre413** [tugrulaltun/BBM412_Final#1]
Şimdi bu dosya Debug ve Release klasörlerinin upload edilmesini engelliyo. Ama model dosyalarının falan bu klasörlerde bulunması gerekiyor. Aksi halde siz hep Visual Studio içinden çalıştırmak zorunda kalacaksınız. Değiştiriyim mi bu dosyayı?

**Comment by tugrulaltun** [comment]
Şimdilik gerek yok sanırım.

**Comment by emre413** [comment]
Tamamdır o zaman. Kalsın şimdilik belki projeyi en son deneme aşamasına gelince düzenleriz.
